name: Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        jdk: [zulu@1.8]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        scala: [2.12.12, 2.13.4]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
          java-version: 1.8

    - name: Mount caches
      uses: actions/cache@v2
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.cache/coursier
        key: ${{ runner.os }}-sbt-${{matrix.scala}}-${{ hashFiles('**/*.sbt') }}

    - name: Formatting
      run: |
        sbt scalafmtCheck test:scalafmtCheck scalafmtSbtCheck

    - name: Compile and test
      run: |
        sbt ++${{matrix.scala}} compile test
